#!/bin/sh

# This will cause the shell to exit immediately
# if a simple command exits with a nonzero exit value.
set -e

# Before push, ensure your build state succeeds. Abort if false.
npm run-script build

# Exit successfully if build succeeds.
exit 0
